# Generated by Django 2.1.3 on 2019-02-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vk',
            field=models.URLField(default='vk.com'),
        ),
    ]
