# Generated by Django 2.1.3 on 2019-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_vk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='koordinates',
            field=models.TextField(default='[55.684758, 37.738521]'),
        ),
    ]
