# Generated by Django 2.1.3 on 2019-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_kx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='kx',
            new_name='kxInt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='koordinates',
        ),
        migrations.AddField(
            model_name='student',
            name='kxDecimal',
            field=models.BigIntegerField(default='684758'),
        ),
        migrations.AddField(
            model_name='student',
            name='kyDecimal',
            field=models.BigIntegerField(default='738521'),
        ),
        migrations.AddField(
            model_name='student',
            name='kyInt',
            field=models.BigIntegerField(default='37'),
        ),
    ]
